[MMB-141] Component Locking
ably-labs/realtime-examples pull request #61
Opened 2023-08-25 21:18 UTC by artismarti

2023-09-05 11:05 UTC, dpiatek requested changes
Some minor comments, otherwise looks great!

2023-09-05 13:18 UTC, artismarti commented on src/components/ComponentLocking/README.md
> +- [Yarn](https://yarnpkg.com/) (optional)
We had listed it at optional originally because not everyone uses Yarn! (Could be an NPM user!) :)

2023-09-05 13:51 UTC, ttypic commented on src/components/ComponentLocking/AblyPoweredInput.tsx
> +  const lockedByYou = locked && lockHolder?.connectionId === self?.connectionId;
`locked` is equal to `lockHolder` and will prevent `undefined === undefined`, if you think it will be more clear with self I will fix

2023-09-05 14:14 UTC, dpiatek commented on src/components/ComponentLocking/AblyPoweredInput.tsx
> +  const lockedByYou = locked && lockHolder?.connectionId === self?.connectionId;
can see that now, no change needed then 👍🏻

2023-09-05 14:16 UTC, dpiatek commented on src/components/ComponentLocking/README.md
> +- [Yarn](https://yarnpkg.com/) (optional)
Right, but if there is `yarn.lock` already it makes more sense to just use yarn? Ideally we'd just use npm here but that's out of the scope of this PR. I'll create a ticket for it.

2023-09-05 15:47 UTC, artismarti commented on src/components/ComponentLocking/README.md
> +- [Yarn](https://yarnpkg.com/) (optional)
Makes sense. 😊

2023-09-06 09:21 UTC, ttypic commented on src/components/ComponentLocking/locking.css
> +}
removed it

2023-09-06 09:21 UTC, ttypic commented on src/components/ComponentLocking/README.md
> +- [Yarn](https://yarnpkg.com/) (optional)
removed optional for now

2023-09-06 09:23 UTC, ttypic commented on src/components/ComponentLocking/InputCell.tsx
> +    : (lockHolder?.profileData?.memberName as string);
I used template string, this way it's without explicit casting and without additional code (which are believe nice for example)

2023-09-06 10:33 UTC, dpiatek approved these changes

2023-09-06 10:33 UTC, dpiatek commented on src/components/ComponentLocking/InputCell.tsx
> +    : (lockHolder?.profileData?.memberName as string);
fair enough 👍🏻

2023-09-06 10:35 UTC, dpiatek commented on src/components/ComponentLocking/locking.css
> +}
(think it's still there but I don't think it's an issue)

2023-09-06 10:51 UTC, merged